/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-08-11 16:07:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from teamfox.co/themes/pleasure/app/admin1/ by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 25 Jun 2015 06:27:49 GMT -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("<title>PENHCHET CHATTING</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Pleasure is responsive, material admin dashboard panel\">\r\n");
      out.write("<meta name=\"author\" content=\"Teamfox\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, height=device-height, initial-scale=1\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\"\r\n");
      out.write("\tcontent=\"black-translucent\">\r\n");
      out.write("<meta name=\"apple-touch-fullscreen\" content=\"yes\">\r\n");
      out.write("<!-- BEGIN CORE CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/admin1/css/admin1.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/css/elements.css\">\r\n");
      out.write("<!-- END CORE CSS -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN PLUGINS CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/plugins/rickshaw/rickshaw.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/plugins/bxslider/jquery.bxslider.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/css/plugins.css\">\r\n");
      out.write("<!-- END PLUGINS CSS -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN SHORTCUT AND TOUCH ICONS -->\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/img/icons/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/img/icons/apple-touch-icon.png\">\r\n");
      out.write("<!-- END SHORTCUT AND TOUCH ICONS -->\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/plugins/modernizr/modernizr.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"nav-bar-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN ICONS -->\r\n");
      out.write("\t\t<div class=\"nav-menu\">\r\n");
      out.write("\t\t\t<div class=\"hamburger\">\r\n");
      out.write("\t\t\t\t<span class=\"patty\"></span> <span class=\"patty\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"patty\"></span> <span class=\"patty\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"patty\"></span> <span class=\"patty\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--.hamburger-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.nav-menu-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"nav-search\">\r\n");
      out.write("\t\t\t<span class=\"search\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.nav-search-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"nav-user\">\r\n");
      out.write("\t\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/img/faces/tolga-ergin.jpg\"\r\n");
      out.write("\t\t\t\t\talt=\"\"> <span class=\"badge\">3</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--.user-->\r\n");
      out.write("\t\t\t<div class=\"cross\">\r\n");
      out.write("\t\t\t\t<span class=\"line\"></span> <span class=\"line\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--.cross-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.nav-user-->\r\n");
      out.write("\t\t<!-- END OF ICONS -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"nav-bar-border\"></div>\r\n");
      out.write("\t\t<!--.nav-bar-border-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN OVERLAY HELPERS -->\r\n");
      out.write("\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t<div class=\"starting-point\">\r\n");
      out.write("\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--.starting-point-->\r\n");
      out.write("\t\t\t<div class=\"logo\">PENHCHET</div>\r\n");
      out.write("\t\t\t<!--.logo-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.overlay-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"overlay-secondary\"></div>\r\n");
      out.write("\t\t<!--.overlay-secondary-->\r\n");
      out.write("\t\t<!-- END OF OVERLAY HELPERS -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--.nav-bar-container-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"layer-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN MENU LAYER -->\r\n");
      out.write("\t\t<div class=\"menu-layer\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li data-open-after=\"true\"><a href=\"index-2.html\">Dashboard</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.menu-layer-->\r\n");
      out.write("\t\t<!-- END OF MENU LAYER -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN USER LAYER -->\r\n");
      out.write("\t\t<div class=\"user-layer\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs nav-justified\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#messages\" data-toggle=\"tab\">Messages</a></li>\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t<li><a href=\"#notifications\" data-toggle=\"tab\">Notifications <span class=\"badge\">3</span></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#settings\" data-toggle=\"tab\">Settings</a></li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row no-gutters tab-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade in active\" id=\"messages\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-list-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-material message-list\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--.col-->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-send-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"messages\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--.messages-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"send-message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"inputer inputer-blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<textarea rows=\"1\" id=\"txtMessage\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control js-auto-size\" placeholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--.inputer-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button id=\"btnSendMessage\" class=\"btn btn-blue\" type=\"button\">Send</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--.send-message-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--.message-send-container-->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--.col-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"mobile-back\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mobile-back-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ion-android-arrow-back\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--.mobile-back-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--.tab-pane #messages-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--.row-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--.user-layer-->\r\n");
      out.write("\t\t<!-- END OF USER LAYER -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--.layer-container-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN GLOBAL AND THEME VENDORS -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/js/global-vendors.js\"></script>\r\n");
      out.write("\t<!-- END GLOBAL AND THEME VENDORS -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- PLEASURE -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/globals/js/pleasure.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/admin1/js/layout.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tPleasure.init();\r\n");
      out.write("\t\t\tLayout.init();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- END INITIALIZATION-->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".nav-user\").trigger(\"click\");\r\n");
      out.write("\t\t\tvar wsURI = \"ws://\" + document.location.host\r\n");
      out.write("\t\t\t\t\t+ document.location.pathname + \"chat\";\r\n");
      out.write("\t\t\tif (!(\"WebSocket\" in window)) {\r\n");
      out.write("\t\t\t\tconsole.log(\"WebSocket is not support on your browser...\")\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tconsole.log(\"WebSocket is support on your browser...\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//var wsURI = \"ws://localhost:8080/Ch10_WebSocket/whiteboardendpoint\";\r\n");
      out.write("\t\t\tvar connection = new WebSocket(wsURI);\r\n");
      out.write("\t\t\tvar sendedMessage = \"\";\r\n");
      out.write("\t\t\tconnection.binaryType = 'arraybuffer';\r\n");
      out.write("\r\n");
      out.write("\t\t\tconnection.onopen = function(event) {\r\n");
      out.write("\t\t\t\tonOpen(event);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tconnection.onerror = function(event) {\r\n");
      out.write("\t\t\t\tonError(event);\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tconnection.onmessage = function(event) {\r\n");
      out.write("\t\t\t\tonMessage(event);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction onOpen(event) {\r\n");
      out.write("\t\t\t\tconsole.log(\"CONNECTED...\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction onError(event) {\r\n");
      out.write("\t\t\t\tconsole.log(event);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction onMessage(event) {\r\n");
      out.write("\t\t\t\tconsole.log(event.data);\r\n");
      out.write("\t\t\t\tif(sendedMessage==event.data){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar message = \r\n");
      out.write("\t\t\t\t\t'<div class=\"message left\">' +\r\n");
      out.write("\t\t\t\t\t\t'<div class=\"message-text\">'+ event.data +'</div>' +\r\n");
      out.write("\t\t\t\t\t\t\t'<img src=\"'+contextPath+'/resources/assets/globals/img/faces/1.jpg\"' +\r\n");
      out.write("\t\t\t\t\t\t\t\t'class=\"user-picture\" alt=\"\">' +\r\n");
      out.write("\t\t\t\t\t'</div>';\r\n");
      out.write("\t\t\t\t$(\".messages\").append(message);\r\n");
      out.write("\t\t\t\t$('.messages').scrollTop($('.messages')[0].scrollHeight);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction sendMessage(){\r\n");
      out.write("\t\t\t\tif($(\"#txtMessage\").val()==\"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsendedMessage = $(\"#txtMessage\").val();\r\n");
      out.write(" \t\t\t\tvar message = \r\n");
      out.write("\t\t\t\t\t'<div class=\"message right\">' +\r\n");
      out.write("\t\t\t\t\t\t'<div class=\"message-text\">'+$(\"#txtMessage\").val()+'</div>' +\r\n");
      out.write("\t\t\t\t\t\t\t'<img src=\"'+contextPath+'/resources/assets/globals/img/faces/tolga-ergin.jpg\"' +\r\n");
      out.write("\t\t\t\t\t\t\t\t'class=\"user-picture\" alt=\"\">' +\r\n");
      out.write("\t\t\t\t\t'</div>';\r\n");
      out.write("\t\t\t\t$(\".messages\").append(message); \r\n");
      out.write("\t\t\t\tif (connection.readyState != WebSocket.OPEN) {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (connection.bufferedAmount == 0) {\r\n");
      out.write("\t\t\t\t\tconnection.send($(\"#txtMessage\").val());\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#txtMessage\").val('');\r\n");
      out.write("\t\t\t\t$('.messages').scrollTop($('.messages')[0].scrollHeight);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#btnSendMessage\").click(function(){\r\n");
      out.write("\t\t\t\tsendMessage();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#txtMessage\").keydown(function(e){\r\n");
      out.write("\t\t\t\tif(e.keyCode==13){\r\n");
      out.write("\t\t\t\t\tsendMessage();\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
